import { Inter,Orbitron } from "next/font/google";
import Navbar from "./components/Navbar";
import './globals.css'
import Footer from "./components/Footer";


const inter = Inter({ subsets: ["latin"] });
const orbitron = Orbitron({ subsets: ["latin"] });

export const metadata = {
  title: "TechServiceWala",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="relative"> */}

        <Navbar/>
        {/* </div> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
